version: "3.9"

name: authorservice

networks:
  author-net: { driver: bridge }
  edge-net:
    external: true

volumes:
  author_pgdata:

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASS:-12345}
      POSTGRES_DB: ${PG_DB:-StoreAuthor}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:${PG_PORT:-5432}:5432"
    volumes:
      - author_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER:-postgres} -d ${PG_DB:-StoreAuthor}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks: [author-net]

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__AuthorDatabase: "Host=postgres;Database=${PG_DB:-StoreAuthor};Username=${PG_USER:-postgres};Password=${PG_PASS:-12345}"
      ApplyMigrations: "true"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5101:8080"
    networks:
      author-net: {}
      edge-net:
        aliases:
          - authorservice-backend

    restart: unless-stopped
